Algoritmo "laço enquanto"
// Disciplina   : [Lógica de Programação com js]
// Professor   : jailson
// Descrição   : exemplo laço enquanto
// Autor(a)    : laiana
// Data atual  : 09/09/2024
Var
// Seção de Declarações das variáveis 
 contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 enquanto contadora<10 faça
 escreval ("jailson")
 contadora<- contadora+1
 fimenquanto
Fimalgoritmo