Algoritmo "semnome"
// Disciplina   : [Lógica de Programação com js]
// Professor   : jailson costa dos santos
// Descrição   :
// Autor(a)    : Laiana
// Data atual  : 06/09/2024
Var
// Seção de Declarações das variáveis 
 numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Digite um numero")
 leia (numero)
 se numero = 1 entao
 escreval ("domingo")
 fimse

Fimalgoritmo