Algoritmo "escreva a altura da base"
// Disciplina   : [Lógica de Programação com js]
// Professor   : jailson
// Descrição   :calculando a area do quadrado
// Autor(a)    : laiana
// Data atual  : 28/08/2024
Var
// Seção de Declarações das variáveis 
 altura, base, area: inteiro
 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva  ("escreva o lado")
  leia  (lado)
  area <- lado*lado
   escreva ("escreva a base)

Fimalgoritmo